id: I894A4FF6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T00:12:17+00:00'
last_modified: '2022-06-08T13:25:16.858365+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20245
  title: བཟོ་རིག་ཕྱོགས་བསྒྲིགས་རི་ཆེན་སྒྲོམ་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3CB2:
      image_group_id: I8LS20247
      title: Volume 1 of bzo rig phyogs bsgrigs ri chen sgrom bu/
      total_pages: 909
      order: 1
      base_file: 3CB2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
