id: P007031
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20245
  title: བཟོ་རིག་ཕྱོགས་བསྒྲིགས་རི་ཆེན་སྒྲོམ་བུ།
  author: ''
  volumes:
    2db90ca2f602452999ff079d9dcc7540:
      image_group_id: I8LS20247
      title: ''
      volume_number: 1
      total_pages: 909
ebook_metadata:
  title: བཟོ་རིག་ཕྱོགས་བསྒྲིགས་རི་ཆེན་སྒྲོམ་བུ།
  author: ''
  sku: P007031
  cover: cover.jpg
  layers:
  - pagination
